runtime: python310
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/capstone-ch2-ps501:asia-southeast2:db-stuntapp
  INSTANCE_HOST: '127.0.0.1'
  DB_USER: 'root'
  DB_PASS: 'root'
  DB_NAME: 'db_stuntapp'
  DB_PORT: 3306

beta_settings:
  cloud_sql_instances: capstone-ch2-ps501:asia-southeast2:db-stuntapp